name: keycloak-demo-14524
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: 
      - start-dev
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      #KC_LOG_LEVEL: DEBUG
    container_name: keycloak-demo-14524
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "JW:host-gateway"
